# Import `themes` folder
import = [
    "~/.config/alacritty/themes/one_dark.toml"
]

# Environment Variables
[env]
TERM = "xterm-256color"

# General Alacritty Setup
[window]

# Add a Title
title = "Alacritty"
dynamic_title = false

dimensions = {columns = 100, lines = 30}

# Padding around border ( inside the terminal )
padding.x = 5
padding.y = 5

# Decorations can be Full or None
# NOTE: macOS also has Buttonless and Transparent
decorations = "None"

# Make Alacritty Transparent
# WARNING: Does not work with i3?
opacity = 0.8

# Blur Alacritty Transparent Background
# WARNING: works on macOS and KDE Wayland
blur = true

# Font Setup
[font]

# Change font to use JetBrains Nerd Font Mono
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
bold = {family = "JetBrainsMono Nerd Font", style = "Bold"}
italic = {family = "JetBrainsMono Nerd Font", style = "Italic"}
bold_italic = {family = "JetBrainsMono Nerd Font", style = "Bold Italic"}

# Change the Font Size
size = 12
