# Import `themes` folder
import = [
    "~/.config/alacritty/themes/one_dark.toml"
]

# Environment Variables
[env]
TERM = "xterm-256color"

# General Alacritty Setup
[window]

# Add a Title
title = "Alacritty"
dynamic_title = false

dimensions = {columns = 100, lines = 30}

# Padding around border ( inside the terminal )
padding.x = 5
padding.y = 5

# Decorations can be Full or None
# NOTE: macOS also has Buttonless and Transparent
decorations = "None"

# Make Alacritty Transparent
# WARNING: Make sure you have Picom installed
opacity = 0.6

# Blur Alacritty Transparent Background
# WARNING: works on macOS and KDE Wayland
blur = true

# Font Setup
[font]

# Change font to use JetBrains Nerd Font Mono
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
bold = {family = "JetBrainsMono Nerd Font", style = "Bold"}
italic = {family = "JetBrainsMono Nerd Font", style = "Italic"}
bold_italic = {family = "JetBrainsMono Nerd Font", style = "Bold Italic"}

# Change font to use PlemolJP35 Console Nerd Font
# normal = {family = "PlemolJP35 Console NF", style = "Regular"}
# bold = {family = "PlemolJP35 Console NF", style = "Bold"}
# italic = {family = "PlemolJP35 Console NF", style = "Italic"}
# bold_italic = {family = "PlemolJP35 Console NF", style = "Bold Italic"}

# Change font to use Hac Nerd Font Mono
# normal = {family = "Hack Nerd Font Mono", style = "Regular"}
# bold = {family = "Hack Nerd Font Mono", style = "Bold"}
# italic = {family = "Hack Nerd Font Mono", style = "Italic"}
# bold_italic = {family = "Hack Nerd Font Mono", style = "Bold Italic"}

# Change the Font Size
# NOTE: 12 is for JetBrainsMono & PlemolJP35 Console Nerd Fonts
size = 14
# NOTE: 13 is for Hack Nerd Font Mono
# size = 13
