# Command to change the download location
  # Adding this to GitHub Repository, because I always forget how to change it.
    # I have not read the documentations fully ( " -")
-o "d:\Unsorted-Songs\%(title)s.%(ext)s"
