# what to include in prompt
format = """
$directory\
$git_branch\
$git_status\
$fill\
$c\
$python\
$java\
$lua\
$time\
$jobs\
$fill\
$cmd_duration\
$line_break\
$character"""

# add the palette name
palette = "onedark"

# individual options

# directory options
[directory]
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '/'
truncate_to_repo = false

# [directory.substitutions]
# 'Document' = '󰈙'
# 'Downloads' = ''
# 'Music' = '󰽴'
# 'Screenshots' = '󰹘'
# 'GitHub' = ''
# '.config' = ''

# fill options
[fill]
symbol = ' '

# python options
[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = ''
style = 'teal'

# time options
[time]
format = 'at [$time]($style) '
use_12hr = true
style = 'yellow'

# theme / colours

# one dark colour palette
[palettes.onedark]
red = '#e06c75'
yellow = '#e5c07b'
green = '#98c379'
teal = '#56b6c2'
blue = '#61afef'
