console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  blue = '#4fa6ed'
  green = '#8ebd6b'
  lightDark = '#7a818e'
  red = '#e55561'
  teal = '#48b0bd'
  yellow = '#e5c07b'

[secondary_prompt]
  template = '❯ '
  foreground = 'p:green'
  background = 'transparent'

[transient_prompt]
  template = '󰘧 '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if eq .Code 0}}p:green{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  [[blocks.segments]]
    template = '<p:red>[</>{{ .Path }}<p:red>]</>'
    foreground = 'p:blue'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

  [[blocks.segments]]
    template = '[{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}<p:red>*</>{{ end }}<cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>]'
    foreground = 'p:lightDark'
    background = 'transparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'p:yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '󰘧'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if eq .Code 0}}p:green{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
