# Import `themes` folder
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

# Environment Variables
[env]
TERM = "xterm-256color"

# General Alacritty Setup
[window]

# Add a Title
title = "Alacritty"

# Padding around border ( inside the terminal )
padding.x = 5
padding.y = 5

# Decorations can be Full or None
# NOTE: macOS also has Buttonless and Transparent
decorations = "None"

# Make Alacritty Transparent
# WARNING: Does not work with i3?
opacity = 0.9

# Blur Alacritty Transparent Background
# WARNING: works on macOS and KDE Wayland
blur = true

# Font Setup
[font]

# Change font to use JetBrains Nerd Font Mono
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

# Change the Font Size
size = 15
