#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Jan 16 14:55:46 MUT 2024
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=BSL_v8.2.07.1.zip
enableShaders=false
